config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
  }
  devise_scope :user do
    get "sign_in", to: "users/sessions#new"
    get "sign_out", to: "users/sessions#destroy"
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  resources :users, only: [:show, :destroy] do
    member do
      get :following, :followers
    end
  end
  resources :posts do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  resources :notifications, only: :index
end

app/views/shared/_error_messages.html.slim
  - flash.each do |msg_type, msg|
    |  <div class="alert alert-
    = msg_type
    | " role="alert" id="alert"> 
    = msg

app/views/shared/_flash_messages.html.slim
- if flash[:error_messages]
  .alert.alert-danger
    ul
      - flash[:error_messages].each do |msg|
        li
          = msg

app/views/shared/_footer.html.slim
footer.footer
  .container
    .footer-main
      p.footer-logo
        | SHARE CAFE
      p.footer-text
        | Copyright © SHARE CAFE Inc. All rights reserved

app/views/shared/_header.html.slim
header
  nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
    = link_to "ShareCafe", root_path, class: 'navbar-brand'
    .search-box.navigation-link
      = search_form_for @search, url: posts_path do |f|
        = icon 'fas', 'search', class: 'search-icon'
        = f.text_field :shop_name_cont, placeholder: 'カフェを検索', class: 'input'
    - if user_signed_in?
      = render 'shared/notification_bell'
      .navigation-container
        = link_to user_path(current_user), class: 'navigation-link ml-3' do
          - if current_user.image?
            = image_tag current_user.image.to_s, class: "rounded-pill img-icon"
          - else
            i.fas.fa-user-circle.mr-2.user-icon
        = link_to '投稿', new_post_path, class: 'navigation-link text-white ml-3'
      = link_to user_path(current_user), class: 'responsive-icon mr-4'
        = icon('fas', 'user')
      = link_to new_post_path, class: 'responsive-icon'
        = icon('fas', 'pen')

app/views/shared/_notification_bell.html.slim
= link_to notifications_path do
  - if current_user.passive_notifications.where(checked: false).exists?
    span.fa-stack
      = icon('fas', 'bell fa-stack-2x white-bell')
      = icon('fas', 'circle fa-stack-1x n-circle')
  - else
    = icon('fas', 'bell white-bell')