config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
  }
  devise_scope :user do
    get "sign_in", to: "users/sessions#new"
    get "sign_out", to: "users/sessions#destroy"
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  resources :users, only: [:show, :destroy] do
    member do
      get :following, :followers
    end
  end
  resources :posts do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  resources :notifications, only: :index
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @recent_posts = Post.all.order(created_at: :desc).limit(3)
    @higher_rank = Post.create_higher_rank
  end
end

app/views/home/_higher_rank.html.slim
li.col-md-4.col-sm-6.col-xs-12.mt-3
  h4
    | #{post_counter + 1}位
  .posts-box.mb-3
    = link_to post_path(post) do
      .post-image
        - if post.image?
          = image_tag post.image.to_s, class: 'img-fluid rounded-lg recent-img'
        - else
          = image_tag "/assets/default.png", class: 'img-fluid rounded-lg recent-img'
      div
        h5
          = post.shop_name
        h6
          = post.address
        h6
          = post.updated_at.strftime("%Y/%m/%d")
        .icon-box
          .icon-box__item
            i.fas.fa-comment-alt
              = post.comments.count
        = link_to user_path(post.user) do
          .ml-1.mt-2
            - if post.user.image?
              = image_tag post.user.image.to_s, class: "rounded-pill img-icon"
            - else
              i.fas.fa-user-circle.mr-2.user-icon
            = post.user.user_name
        div[class="favorites-button-#{post.id} favorite-btn"]
          = render partial: 'favorites/favorite', locals: { post: post }

app/views/home/_recent_posts.html.slim
.col-md-4.col-sm-6.col-xs-12.mt-3
  .posts-box.mb-3
    = link_to post_path(post) do
      .post-image
        - if post.image?
          = image_tag post.image.to_s, class: 'img-fluid rounded-lg recent-img'
        - else
          = image_tag "/assets/default.png", class: 'img-fluid rounded-lg recent-img'
      div
        h5
          = post.shop_name
        h6
          = post.address
        h6
          = post.updated_at.strftime("%Y/%m/%d")
        .icon-box
          .icon-box__item
            i.fas.fa-comment-alt
              = post.comments.count
        = link_to user_path(post.user) do
          .ml-1.mt-2
            - if post.user.image?
              = image_tag post.user.image.to_s, class: "rounded-pill img-icon"
            - else
              i.fas.fa-user-circle.mr-2.user-icon
            = post.user.user_name
        div[class="favorites-button-#{post.id} favorite-btn"]
          = render partial: 'favorites/favorite', locals: { post: post }

app/views/home/index.html.slim
.home-top.img-fluid
  - if flash[:notice]
    .alert.alert-primary.text-center = flash[:notice]
  .home-top-text.text-center
    .home-top-main-title.text-white
      h1
        | ShareCafe
    .home-top-main-text.text-white
      h4
    .home-top-main-link.mt-5
      - unless user_signed_in?
        = link_to "登録する", new_user_registration_path, class: "btn btn-xs btn-dark rounded-pill"
        = link_to "ログイン", new_user_session_path, class: 'btn btn-xs btn-dark rounded-pill ml-3'
        p
          = link_to "ゲストログイン", users_guest_sign_in_path, method: :post, class: 'btn-animation btn-xs rounded-pill mt-3'
.container.mt-4
  .row.contents-box
    .col-sm-12
      h4 | 最近投稿されたカフェ
    = render partial: "recent_posts", collection: @recent_posts, as: "post"
    .col-sm-12
      = link_to "もっと見る", posts_path, class: 'read-more-btn'
.container.mt-4
  .row.contents-box
    .col-sm-12
      h4 | いいねランキング
    ul.bxslider
      = render partial: "higher_rank", collection: @higher_rank, as: "post"